### ISSUE TITLE
Archive code somewhere

### ISSUE THREAD

**Issue by trashbirdecology** [gsvidaurre/strong-individual-signatures#1]
Repasted from our slack:

I'd like to recommend that, since this is the Supp Mat for a published work that you place in a trusted digital repository somewhere, where the code will be archived and is not subject to change (or archive the Github repository entirely such that it is read-only).

**Comment by gsvidaurre** [comment]
Thanks for this suggestion! The data and code to reproduce the main and supplementary analyses were archived in Dryad following manuscript publication: https://doi.org/10.5061/dryad.w6m905qkg.
